name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/registration-backend:latest ./backend

      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/registration-backend:latest

  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/registration-frontend:latest ./frontend

      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/registration-frontend:latest
